# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_order_ordergoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=32)),
                ('s_phone', models.CharField(max_length=11)),
                ('s_address', models.CharField(max_length=255)),
                ('s_isdefault', models.BooleanField(default=False)),
                ('s_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Users')),
            ],
            options={
                'db_table': 'axf_shopaddress',
            },
        ),
    ]
